name: Make Repo Public

on:
  schedule:
    - cron: "0 4 12 3 *"

jobs:
  make_public:
    runs-on: ubuntu-latest
    steps:
      - name: Make repository public
        run: |
          curl -X PATCH -H "Authorization: token ${{ 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 }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }} \
          -d '{"private": false}'
